### PR TITLE
Update SRC_GIT urls

### PR DESCRIPTION
**Pull request by Herrie82**
git.webos-internals.org was decommissioned quite a while ago. Most things have been imported into wosigh, therefore pointing to there for now, so builds will at least work.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by rwhitby** [comment]
I've temporarily made you an owner.  Please create repositories and set access rights so that you can continue work without needing to be an owner.

**Comment by rwhitby** [comment]
Let's keep the non-core applications at wosigh rather than webos-internals.  Let me know when you no longer need to be an owner at webos-internals.

**Comment by Herrie82** [comment]
@rwhitby Thanks for swift reply, where would you put the boundary between core and non-core? Games are non-core I'd say. Apps with an org.webosinternals appID are core, others non-core?`

In that case I'd have the following divide:
**core:**
kernel-patches
KeyBoss
Speechd
FreeTether
gsmwav
Impostah
lunamanager
navit
navit-maps
oldmodeswitcher
saverestore
showprops
terminal
wirc
xserver
zcorder
hello
upstartmanager
locale
ledmanager
upstartmgr

**non-core:**
tetricrisis
drbattery (though this should be core I'd say?)
duke3d
fishfillets
jstop (though this should be core I'd say?)
myflashlight
netstat
ntpsync
sdldoom
sdlquake
stella
supertux
terminus 
tiddlywiki
visualboyadvance
wolui
ompload
sets

**Comment by Herrie82** [comment]
@rwhitby OK my divide is fine then. Will work on that basis and let you know once done.

**Pull request merged**
