### PR TITLE
OpenSSL Updater 0.9.8-6 alpha version

### PR DESCRIPTION
**Pull request by tgaillar**

### CODE REVIEW

**Comment by tgaillar** [comment]
Thank you Rod! :-) ThibaudOn 12 Oct 2015 13:33, Rod Whitby <notifications@github.com> wrote: Merged #40.

**Comment by tgaillar** [comment]
Hi Rod,

I am seeing http://ipkg.preware.net/feeds/ being updated every 15 minutes for quite some time now, just endlessly updating the ```Packages```, ```Packages.gz``` & ```Packages.stamps```.

Anything wrong?

**Comment by tgaillar** [comment]
Hi Rod,

It seems you have activated http://ipkg.preware.net/feeds/ update on a regular basis, but I am not seeing any update to http://ipkg.preware.net/alpha/, which means [OpenSSL-Updater](http://www.github.com/tgaillar/OpenSSL-Updater/wiki/) **does not get published in the Preware feed**.

Please could you update the http://ipkg.preware.net/alpha/ feed? Or is there any reason not to?

Thank you

**Comment by rwhitby** [comment]
There are some errors in the build which need to be fixed by the developers submitting:

( cd build ; git clone -l ../git `basename git://github.com/webos-internals/tweaks.git .git` ; cd `basename git://githu\
b.com/webos-internals/tweaks.git .git` ; git checkout "v3.0.2" )
Initialized empty Git repository in /srv/preware/build/apps/tweaks/build/tweaks/.git/error: pathspec 'v3.0.2' did not match any file(s) known to git.
make[1]: *** [../../downloads/tweaks-3.0.2.tar.gz] Error 1

This may be stopping later builds.

— Rod

**Comment by tgaillar** [comment]
Yes, that's what I was fearing, thanks for the insight.

Had a quick look: [http://github.com/webos-internals/tweaks is no later than v3.0.1](https://github.com/webos-internals/tweaks/tags), so I suspect (ka6sox?) may have forgotten to push v3.0.2 while [updating the build Makefile](https://github.com/webos-internals/build/commit/e831b603c5c97c2ec614827d3e737e021924c43a). Downgrading to v3.0.1 as a quick workaround? ;-)

I see the alpha feed updating now, so you got a fix anyway!

I'll be away the whole week-end, so I'll only be able to kick-off OpenSSL Updater in webOS Nation forums late Sunday (my time).

Thank you for your support, much appreciated. :-)

**Pull request merged**
